### ISSUE TITLE
Dependency Java 8?

### ISSUE THREAD

**Issue by lucasfsousa** [logzio/logzio-logback-appender#13]
I'm testing Logz and using this dependency, when I tried to run the application I got this error:
Caused by: java.lang.UnsupportedClassVersionError: io/logz/logback/LogzioLogbackAppender : Unsupported major.minor version 52.0

This dependency needs that the application use Java 8?

**Comment by roiravhon** [comment]
Hey @lucasfsousa!
Yes, this appender requires java 8 as you can see in the pom.xml
https://github.com/logzio/logzio-logback-appender/blob/master/pom.xml#L46

I'll add it to the readme as well.

LMK if there is anything else i can help with

**Comment by lucasfsousa** [comment]
Hi @roiravhon, thanks for the reply.
Is there any way to use this in Java 7 application?

I want to use logback because the configuration for log4j needs to change somethings in the server...

**Comment by roiravhon** [comment]
Unfortunately, currently no.
This code relies heavily on java 8 features and would be hard to convert.

**Comment by lucasfsousa** [comment]
No problem @roiravhon, thank you again.

**Comment by jemshit** [comment]
Will it work on Android (limited support to Java 8 afaik) ? @roiravhon

**Comment by roiravhon** [comment]
Never tested. You can try and let us know :)
