### ISSUE TITLE
Bug: no applicable action for [inMemoryLogsCountLimit]

### ISSUE THREAD

**Issue by ayltai** [logzio/logzio-logback-appender#60]
The property setter and getter are incorrectly named. For getter, it is `inMemoryLogsCountLimit` but the setter is `inMemoryLogsCountCapacity`. README also mentions to use inMemoryLogsCountLimit property but this won't work. It should be `inMemoryLogsCountCapacity`.

**Comment by idohalevi** [comment]
@ayltai Thank you. I will try to address it soon

**Comment by idohalevi** [comment]
#62
