### ISSUE TITLE
Add method to drain message queue manually

### ISSUE THREAD

**Issue by klya** [logzio/logzio-logback-appender#74]
Our Amazon instances don't stop java processes before termination, so ShutdownHook can't be used to drain log queues.

Add method to flush them manually.

Fix: #72

**Comment by yyyogev** [comment]
Thanks

**Comment by klya** [comment]
OK, waiting for 1.0.25 release.

**Comment by yyyogev** [comment]
Maven Central usually takes a couple of days to update

**Comment by klya** [comment]
OK

**Comment by klya** [comment]
It looks like Maven Central will never update:
1. Tagged commit has `0-SNAPSHOT` version
2. Tag has wrong format: `v.1.0.25` (extra dot, other versions don't have vee)
Looks like some build-chain bug.

**Comment by yyyogev** [comment]
You are right, I think our deploy key is outdated.. I need to check
Thanks again

**Comment by klya** [comment]
Any news? 1.0.25 still hasn't available on maven central.

**Comment by yyyogev** [comment]
Sorry, not yet.. It's been a busy week and we have some permission approval delays. We'll get to it soon.

**Comment by yyyogev** [comment]
@klya the push is now verified, Maven central should update soon

**Comment by klya** [comment]
OK, waiting for Maven central.

**Comment by klya** [comment]
Works fine, thanks!
