### ISSUE TITLE
Error with AspectJ compiler since 1.0.24

### ISSUE THREAD

**Issue by benjavalero** [logzio/logzio-logback-appender#76]
I have just started using Logz.io so I have added the `logzio-logback-appender` dependency to my Java project.

In this project I am using AspectJ to add behaviour to some methods. However on compilation time there is an error with one of the shaded dependencies of the appender. The application starts but no aspect is applied:

```
java.lang.IllegalStateException: Expecting .,<, or ;, but found logbackappender while unpacking <T:Ljava/lang/Object;>Lio/logz/logback-appender/sender/com/google/common/base/Optional<TT;>;
```

The rest of the error: [ajcore.20201124.181250.487.txt](https://github.com/logzio/logzio-logback-appender/files/5591558/ajcore.20201124.181250.487.txt)

Curiously everything works fine with version 1.0.23, so at least I am not blocked.

Any hint?

Thanks in advance,

**Comment by yyyogev** [comment]
Hi @benjavalero 
Is the appender on debug mode?

**Comment by benjavalero** [comment]
> Hi @benjavalero
> Is the appender on debug mode?

Sorry, I am not sure what are you asking me about. I have used the appender configuration as recommended in the documentation:
```
<appender name="LogzioLogbackAppender" class="io.logz.logback.LogzioLogbackAppender">
	<token>WozucGtGpadrwOjZSeMgWbzbwGuOmtBY</token>
	<logzioUrl>https://listener-eu.logz.io:8071</logzioUrl>
	<logzioType>java</logzioType>
	<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
		<level>DEBUG</level>
	</filter>
</appender>
```

Please note again that this error happens **on compilation time**. Thanks again.

**Comment by yyyogev** [comment]
Could you please try and run with these configurations:
`<appender name="LogzioLogbackAppender" class="io.logz.logback.LogzioLogbackAppender">
	<token>YOURTOKEN</token>
	<logzioUrl>https://listener-eu.logz.io:8071</logzioUrl>
	<logzioType>java</logzioType>
	<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
		<level>DEBUG</level>
	</filter>
</appender>`

So we could get more context information
Thanks

**Comment by benjavalero** [comment]
> Could you please try and run with these configurations:
> `<appender name="LogzioLogbackAppender" class="io.logz.logback.LogzioLogbackAppender"> <token>YOURTOKEN</token> <logzioUrl>https://listener-eu.logz.io:8071</logzioUrl> <logzioType>java</logzioType> <filter class="ch.qos.logback.classic.filter.ThresholdFilter"> <level>DEBUG</level> </filter> </appender>`
> 
> So we could get more context information
> Thanks

Thanks for your help. Nevertheless the configuration you have given is exactly the same one I am applying (see my previous comment).

Anyway I guess it is not a problem with the appender itself, but something strange with the dependencies which have been _shaded_ in the package since version 1.0.24.

Honestly I have no idea why this happens.  Just for curiosity, why shading some dependencies instead of simply declaring them in the POM as usual in Maven?

**Comment by yyyogev** [comment]
Sorry, I thought I added the debug option but I just copy-paste yours with no changes.. This is the config you should use to get debug logs:
```
<appender name="LogzioLogbackAppender" class="io.logz.logback.LogzioLogbackAppender">
	<token>xxxxxxxxxxxx</token>
	<logzioUrl>https://listener-eu.logz.io:8071</logzioUrl>
	<logzioType>java</logzioType>
        <debug>true</debug>
	<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
		<level>DEBUG</level>
	</filter>
        <root level="debug">
            <appender-ref ref="LogzioLogbackAppender"/>
        </root>
</appender>
```

We shaded some dependencies to prevent collisions with outer dependencies from the parent project

**Comment by benjavalero** [comment]
I am closing this issue because I cannot reproduce it anymore after removing the _module-info.java_ file (not actually needed) from my project and also removing the AspectJ plugin which was causing the problem. I am also using now version _v1.0.25_ (yes, with a _v_, I guess this is right).

Thanks for the help.
