### ISSUE TITLE
Library not send logs from logback to logz

### ISSUE THREAD

**Issue by wagnerww** [logzio/logzio-logback-appender#81]
Hi, I'm not able to send my logs to logz. I've already looked in the documentation and apparently everything is ok. My application is in spring boot, version 2.2.8.RELEASE. O token esta correto, e a região é us-east-1.

what could be wrong? I don't know what else to do to integrate, the logs just don't come to logz.io

My pom.xml in the logs settings:

     <dependency>
	      <groupId>org.slf4j</groupId>
	      <artifactId>log4j-over-slf4j</artifactId>
	     <version>1.7.13</version>
    </dependency>
    <dependency>
            <groupId>io.logz.logback</groupId>
           <artifactId>logzio-logback-appender</artifactId>
           <version>1.0.24</version>
    </dependency>
    <dependency>
	   <groupId>ch.qos.logback</groupId>
	   <artifactId>logback-classic</artifactId>
	   <version>1.2.3</version>
    </dependency>
    <dependency>
	    <groupId>ch.qos.logback</groupId>
	     <artifactId>logback-core</artifactId>
	     <version>1.2.0</version>
     </dependency>
     
   My logback.xml, I also tested using the logback-spring.xml:
   
   <configuration>

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <property resource="application.yaml" />

    <springProperty name="app_name" source="spring.application.name"/>
    <springProperty name="profile" source="spring.profiles"/>

    <property name="CONSOLE_LOG_PATTERN" value="${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>${CONSOLE_LOG_PATTERN}</pattern>
            <charset>UTF-8</charset>
        </encoder>
    </appender>

     
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>
    <appender name="LOGZIO" class="io.logz.logback.LogzioLogbackAppender">
        <token>${mytoken}</token>
        <logzioUrl>https://listener.logz.io:8071</logzioUrl>
        <logzioType>apptest</logzioType>
    </appender>

    
    <root level="INFO">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="LOGZIO"/>
    </root>

</configuration>

**Comment by caodangtinh** [comment]
Can you try to add below configuration attribute to logback-spring.xml file?
`<configuration debug="true">`

Then you will see debug log and what happen behind the scene.
